/**
 * Workday CANARY — a controlled subset, never the full 104.
 *
 * Deliberately does NOT add WORKDAY to CRAWLABLE_PROVIDERS. The scheduler would
 * then hand out all 104 tenants, and every expensive lesson this project has
 * learned says a green test suite is not evidence of production behaviour:
 * empty-board deletion, Workable false detection, the missing scheduler, the
 * IPv6 outage, the stale worker config — all passed their tests first.
 *
 * The cohort covers every API behaviour measured on 2026-08-20:
 *   locationCountry facet   adobe, agilent
 *   locations facet         citi, barclays
 *   no location facet       spgi, db
 *   repeated pagination     fractal, nxp
 *   high volume             accenture   (total caps at 2000, ~43k India jobs)
 *
 *   npx tsx src/scripts/workday-canary.ts          # fetch + measure only
 *   npx tsx src/scripts/workday-canary.ts --ingest # also sync through the API
 */
import { readFileSync } from 'node:fs';
import { workdayAdapter, workdayLastStats, parseIdentifier } from '../adapters/workday';
import { ApiClient } from '../api-client';

/**
 * Cohort file: `companyId <TAB> atsIdentifier` per line, generated by psql.
 *
 * The canary cannot use /internal/companies/due — that endpoint only returns
 * CRAWLABLE_PROVIDERS, and Workday is deliberately excluded until this canary
 * passes. Reading Postgres directly from a worker would violate ADR-2
 * (single-writer ingest; workers never touch the database), so the cohort is
 * handed in instead.
 */
function loadCohort(path: string): Map<string, { companyId: string; identifier: string }> {
  const out = new Map<string, { companyId: string; identifier: string }>();
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    const [companyId, identifier] = line.trim().split('\t');
    if (!companyId || !identifier) continue;
    out.set(identifier.split('/')[0], { companyId, identifier });
  }
  return out;
}

const CANARY = [
  { tenant: 'adobe', why: 'locationCountry facet' },
  { tenant: 'agilent', why: 'locationCountry facet' },
  { tenant: 'citi', why: 'locations facet' },
  { tenant: 'barclays', why: 'locations facet' },
  { tenant: 'spgi', why: 'no location facet' },
  { tenant: 'db', why: 'no location facet' },
  { tenant: 'fractal', why: 'repeated pagination' },
  { tenant: 'nxp', why: 'repeated pagination' },
  { tenant: 'accenture', why: 'high volume / total capped at 2000' },
];

interface Row {
  tenant: string;
  why: string;
  companyId?: string;
  identifier?: string;
  ms: number;
  listed: number;
  candidates: number;
  detailFetched: number;
  detailFailed: number;
  accepted: number;
  pages: number;
  repeatedPage: boolean;
  facetFiltered: boolean;
  error?: string;
  synced?: { found: number; created: number; removed: number };
}

async function main(): Promise<void> {
  const ingest = process.argv.includes('--ingest');
  const cohortPath = process.argv.find((a) => a.endsWith('.tsv'));
  if (!cohortPath) {
    console.error('usage: workday-canary.ts <cohort.tsv> [--ingest]');
    process.exit(1);
  }
  const cohort = loadCohort(cohortPath);
  // Constructed only when actually ingesting: fetch-only needs no API access,
  // and ApiClient throws on a missing INTERNAL_API_TOKEN. A measurement pass
  // should never be blocked by a credential it does not use.
  const api = ingest ? new ApiClient() : null;

  console.log(`Workday canary — ${CANARY.length} tenants · ingest=${ingest}\n`);

  const rows: Row[] = [];
  for (const c of CANARY) {
    const match = cohort.get(c.tenant);
    const identifier = match?.identifier;

    if (!identifier || !parseIdentifier(identifier)) {
      rows.push({
        ...c, ms: 0, listed: 0, candidates: 0, detailFetched: 0, detailFailed: 0,
        accepted: 0, pages: 0, repeatedPage: false, facetFiltered: false,
        error: identifier ? `unparseable identifier "${identifier}"` : 'not in cohort file',
      });
      console.log(`  ${c.tenant.padEnd(12)} SKIPPED — ${rows[rows.length - 1].error}`);
      continue;
    }

    const t0 = Date.now();
    try {
      const board = await workdayAdapter.fetchBoard!(identifier);
      const jobs = board.jobs;
      const ms = Date.now() - t0;
      const s = workdayLastStats();
      const row: Row = {
        ...c, companyId: match!.companyId, identifier, ms,
        listed: s?.listed ?? 0,
        candidates: s?.indiaCandidates ?? 0,
        detailFetched: s?.detailFetched ?? 0,
        detailFailed: s?.detailFailed ?? 0,
        accepted: jobs.length,
        pages: s?.pages ?? 0,
        repeatedPage: s?.repeatedPage ?? false,
        facetFiltered: s?.facetFiltered ?? false,
      };

      if (ingest && jobs.length > 0) {
        // The REAL ingest path — same reconciliation guards as every other
        // source. A Workday crawl may only retire source='workday' rows, so
        // existing FreeHire jobs at these companies must survive untouched.
        //
        // board.complete is passed EXPLICITLY rather than left to default: five
        // of these nine tenants hit the page cap, and a canary that quietly
        // claimed a complete board would be a measurement tool causing the very
        // damage it exists to rule out.
        if (!board.complete) {
          console.log(`  ${c.tenant}: PARTIAL board (${board.reason}) — retiring nothing`);
        }
        row.synced = await api!.syncCompanyJobs(
          match!.companyId,
          'workday',
          jobs,
          board.complete,
        );
      }
      rows.push(row);
      console.log(
        `  ${c.tenant.padEnd(12)} listed=${String(row.listed).padEnd(5)} cand=${String(row.candidates).padEnd(5)} ` +
          `accepted=${String(row.accepted).padEnd(5)} pages=${String(row.pages).padEnd(3)} ` +
          `${row.repeatedPage ? 'REPEAT ' : ''}${row.facetFiltered ? 'facet' : 'local'} ${ms}ms` +
          (row.synced ? `  → created=${row.synced.created} removed=${row.synced.removed}` : ''),
      );
    } catch (err) {
      rows.push({
        ...c, identifier, ms: Date.now() - t0, listed: 0, candidates: 0, detailFetched: 0,
        detailFailed: 0, accepted: 0, pages: 0, repeatedPage: false, facetFiltered: false,
        error: (err as Error).message,
      });
      console.log(`  ${c.tenant.padEnd(12)} ERROR — ${(err as Error).message}`);
    }
  }

  // ---- summary --------------------------------------------------------------
  const ok = rows.filter((r) => !r.error);
  const sum = (f: keyof Row) => ok.reduce((a, r) => a + (Number(r[f]) || 0), 0);
  const lat = ok.map((r) => r.ms).sort((a, b) => a - b);

  console.log('\n==============================================================');
  console.log(' WORKDAY CANARY RESULT');
  console.log('==============================================================');
  console.log(`tenants attempted        ${rows.length}`);
  console.log(`  succeeded              ${ok.length}`);
  console.log(`  errored                ${rows.length - ok.length}`);
  console.log(`listings fetched         ${sum('listed')}`);
  console.log(`India candidates         ${sum('candidates')}`);
  console.log(`detail requests          ${sum('detailFetched')}`);
  console.log(`  failed                 ${sum('detailFailed')}`);
  const df = sum('detailFetched');
  console.log(`  success rate            ${df ? (100 * (df - sum('detailFailed')) / df).toFixed(1) : '-'}%`);
  console.log(`ACCEPTED (India+fresh)   ${sum('accepted')}`);
  console.log(`pages fetched            ${sum('pages')}`);
  console.log(`repeated-page stops      ${ok.filter((r) => r.repeatedPage).length} -> ${ok.filter((r) => r.repeatedPage).map((r) => r.tenant).join(', ') || 'none'}`);
  console.log(`facet-filtered tenants   ${ok.filter((r) => r.facetFiltered).length} / ${ok.length}`);
  console.log(`per-tenant wall time     p50 ${lat[Math.floor(lat.length / 2)] ?? 0}ms · max ${lat[lat.length - 1] ?? 0}ms`);

  if (ingest) {
    console.log(`\ningest: created=${ok.reduce((a, r) => a + (r.synced?.created ?? 0), 0)} ` +
      `removed=${ok.reduce((a, r) => a + (r.synced?.removed ?? 0), 0)}  <-- removed MUST be 0`);
  }

  const errs = rows.filter((r) => r.error);
  if (errs.length) {
    console.log('\n--- errors ---');
    for (const e of errs) console.log(`  ${e.tenant.padEnd(12)} ${e.error}`);
  }

  console.log('\n--- per tenant ---');
  console.log('tenant'.padEnd(13) + 'behaviour'.padEnd(30) + 'listed  cand   accepted  pages');
  for (const r of rows) {
    console.log(
      r.tenant.padEnd(13) + r.why.padEnd(30) +
      String(r.listed).padEnd(8) + String(r.candidates).padEnd(7) +
      String(r.accepted).padEnd(10) + String(r.pages),
    );
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
