-- Backfill: job.country → ISO 3166-1 alpha-2.
--
-- Every surface filters on `country = 'IN' OR workMode = 'REMOTE'`. Workable
-- and Recruitee passed their source's locale string through unchanged, so the
-- corpus held 567 ACTIVE India jobs stored as the literal string 'India',
-- invisible to Browse, Today, matching and notifications alike — including one
-- evaluated APPLY at 77.3 the user could never see. Singapore (246),
-- Malaysia (212) and United States (203) had the same problem, and Recruitee
-- emits German locale names ('Deutschland').
--
-- New rows are normalized at ingest (`normalizeCountry`, ingest.service.ts), so
-- this only repairs history. The mapping below was GENERATED by running that
-- same function over `SELECT DISTINCT country` — it cannot drift from the code
-- silently, and country.spec.ts asserts each of these pairs.
--
-- 'worldwide' is deliberately absent: it is a remote scope, not a market, and
-- is left as-is rather than being assigned a country the job is not in.

UPDATE jobs j
SET country = m.iso
FROM (VALUES
  ('Albania', 'AL'),
  ('Algeria', 'DZ'),
  ('Argentina', 'AR'),
  ('Armenia', 'AM'),
  ('Australia', 'AU'),
  ('Belgium', 'BE'),
  ('Brazil', 'BR'),
  ('Bulgaria', 'BG'),
  ('Canada', 'CA'),
  ('Colombia', 'CO'),
  ('Czechia', 'CZ'),
  ('Deutschland', 'DE'),
  ('Egypt', 'EG'),
  ('France', 'FR'),
  ('Germany', 'DE'),
  ('Honduras', 'HN'),
  ('Hong Kong', 'HK'),
  ('Hungary', 'HU'),
  ('India', 'IN'),
  ('Indonesia', 'ID'),
  ('Ireland', 'IE'),
  ('Israel', 'IL'),
  ('Japan', 'JP'),
  ('Luxembourg', 'LU'),
  ('Malaysia', 'MY'),
  ('Mexico', 'MX'),
  ('Nepal', 'NP'),
  ('Netherlands', 'NL'),
  ('New Zealand', 'NZ'),
  ('Philippines', 'PH'),
  ('Poland', 'PL'),
  ('Portugal', 'PT'),
  ('Romania', 'RO'),
  ('Saudi Arabia', 'SA'),
  ('Singapore', 'SG'),
  ('Slovakia', 'SK'),
  ('South Africa', 'ZA'),
  ('South Korea', 'KR'),
  ('Spain', 'ES'),
  ('Taiwan', 'TW'),
  ('Thailand', 'TH'),
  ('Turkey', 'TR'),
  ('United Arab Emirates', 'AE'),
  ('United Kingdom', 'GB'),
  ('United States', 'US'),
  ('Vietnam', 'VN')
) AS m(name, iso)
WHERE j.country = m.name;
